version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: 'rapidfort/etcd:latest'
    environment:
      - ETCD_NAME=infra0
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # - ETCD_LISTEN_CLIENT_URLS=http://etcd0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd0:2380,infra1=http://etcd1:2380,infra2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 12379:2379
      - 12380:2380
    networks:
      - app-tier

  etcd1:
    image: 'rapidfort/etcd:latest'
    environment:
      - ETCD_NAME=infra1
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # - ETCD_LISTEN_CLIENT_URLS=http://etcd1:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd0:2380,infra1=http://etcd1:2380,infra2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 1111:2379
      - 22380:2380
    networks:
      - app-tier

  etcd2:
    image: 'rapidfort/etcd:latest'
    environment:
      - ETCD_NAME=infra2
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # - ETCD_LISTEN_CLIENT_URLS=http://etcd2:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd0:2380,infra1=http://etcd1:2380,infra2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 32379:2379
      - 32380:2380
    networks:
      - app-tier